SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO AS P
JOIN ITEM_TREE AS T
on P.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO AS C
on T.ITEM_ID = C.ITEM_ID
WHERE P.RARITY='RARE'
ORDER BY C.ITEM_ID DESC
